apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-role
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ template "fullname" . }}
